In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\python3.9.5\python.exe -m pip install --upgrade pip' command.


In [ ]:
import numpy as np

arr_a = np.array([1,3,4,6])
print(type(arr_a))
print(arr_a.size)
print(arr_a.dtype)

print("\n After reshaping")
arr_a = np.reshape(arr_a,(2,2))
print('Size =',arr_a.size)
print('data type =',arr_a.dtype)
print('dimension =',arr_a.ndim)
print('shape =',arr_a.shape)
print(arr_a)

In [4]:
arr_b = np.array([[1,3,4,6],[7,8,9,10], [12,34,54,16]])
print(type(arr_b))
print('Size =',arr_b.size)
print('data type =',arr_b.dtype)
print('dimension =',arr_b.ndim)
print('shape =',arr_b.shape)
print(arr_b)

print("\n After reshaping")
arr_b = arr_b.reshape(2,6)
print('Size =',arr_b.size)
print('data type =',arr_b.dtype)
print('dimension =',arr_b.ndim)
print('shape =',arr_b.shape)
print(arr_b)

<class 'numpy.ndarray'>
Size = 12
data type = int32
dimension = 2
shape = (3, 4)
[[ 1  3  4  6]
 [ 7  8  9 10]
 [12 34 54 16]]

 After reshaping
Size = 12
data type = int32
dimension = 2
shape = (2, 6)
[[ 1  3  4  6  7  8]
 [ 9 10 12 34 54 16]]


In [6]:
arr_c = np.arange(2,20,2)
print(arr_c)
arr_c = arr_c.reshape(3,3)
print(arr_c)

[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
arr_ones = np.ones(8)
print(arr_ones)

arr_zeros = np.zeros(8)
print(arr_zeros)

[1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
arr_c = np.arange(2,20,2)
arr_c = arr_c.reshape(3,3)
print('array c')
print(arr_c)
arr_d = arr_c*3
print('array d')
print(arr_d)

arr_f = arr_d - arr_c
print('array f')
print(arr_f)

array c
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
array d
[[ 6 12 18]
 [24 30 36]
 [42 48 54]]
array f
[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [15]:
arr_g = np.linspace(10,20,5)
print(arr_g)

[10.  12.5 15.  17.5 20. ]


In [4]:
arr_h = np.random.rand(3,2,2)
print(arr_h)

arr_i = np.random.random()
print(arr_i)

[[[0.79364532 0.64523986]
  [0.55272621 0.63134368]]

 [[0.27674017 0.86785357]
  [0.03939236 0.18735305]]

 [[0.07067113 0.56785286]
  [0.58693553 0.93482423]]]
0.42868916406570123
